config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'search' => 'searchs#home'
  post 'search' => 'searchs#find'
  get 'password_resets/edit'
  get 'profile' => 'static_pages#profile'
  post 'unlike' => 'likes#destroy'
  get 'client/users' => 'users#java_client'
  get 'client/messages' => 'messages#java_client'

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'remove_friend' => 'users#unfriend'
  post 'quit_dialog' => 'dialogs#quit'
  delete 'unlike' => 'likes#destroy'
  resources :users do
    member do
      get 'dialogs' => 'dialogs#user'
    end

  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :friend_requests, only: [:create, :update]
  resources :posts, only: [:create, :destroy]
  resources :dialogs, only: [:create, :update, :new, :show]
  resources :messages, only: [:create]
  resources :likes, only: [:create]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase
  before_create :create_activation_digest
  validates :username, presence: true, length: { minimum: 4, maximum: 40 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, multiline: true }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 4 }, allow_blank: true
  has_many :friendship_relations, class_name: 'Friendship', foreign_key: 'to_id', dependent: :destroy
  has_many :friends, through: 'friendship_relations', source: :from_friend
  has_many :friend_requests, foreign_key: 'to_id'
  has_many :active_posts, class_name: 'Post', foreign_key: 'from_id'
  has_many :passive_posts, class_name: 'Post', foreign_key: 'to_id'
  has_many :dialog_relations, foreign_key: 'user_id', class_name: 'DialogRelationship'
  has_many :dialogs, through: :dialog_relations, source: :dialog
  has_many :messages
  has_many :notifications
  mount_uploader :avatar, AvatarUploader
  validate :avatar_size

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.friends?(user_one, user_two)
    user_one.is_friend?(user_two) && user_two.is_friend?(user_one)
  end

  def wall
    self.passive_posts.order(created_at: :desc)
  end

  def feed
    friend_ids = 'SELECT from_id FROM friendships WHERE to_id = :user_id'
    Post.where("to_id IN (#{friend_ids}) OR to_id = :user_id", user_id: id).order(created_at: :desc)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # Nice and simple example of Metaprogramming
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute :reset_digest, User.digest(reset_token)
    update_attribute :reset_sent_at, Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def make_friends(user)
    raise 'Already friends' if User.friends?(self, user)
    raise 'Cannot make friend of yourself' if self == user
    Friendship.create(from_id: self.id, to_id: user.id)
    Friendship.create(from_id: user.id, to_id: self.id)
  end

  def unfriend(user)
    raise 'Not a friend' unless self.is_friend?(user)
    id = Friendship.where('from_id = (?) AND to_id = (?)', self.id, user.id)[0].id
    Friendship.find_by(id: id).destroy
    id = Friendship.where('from_id = (?) AND to_id = (?)', user.id, self.id)[0].id
    Friendship.find_by(id: id).destroy
    # Friendship.where(from_id: self.id, to_id: user.id).destroy
  end

  def is_friend?(user)
    friends.include? user
  end

  def is_member_of(dialog)
    dialogs.include?(dialog)
  end

  def has_dialog_with(user)
    dialogs.each do |dialog|
      return true if dialog.members.include?(user) && dialog.members.count == 2
    end
    false
  end

  def notification_exists?(dialog)
    notifications.include?(Notification.find_by(dialog_id: dialog.id))
  end

  private
  def downcase
    self.username = username.downcase
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def avatar_size
    if avatar.size > 5.megabytes
      errors.add(:avatar, "should be less than 5MB")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_logged_in?, except: [:new, :create, :edit, :update, :java_client]

  def new
    @user = User.new
  end

  def index # All users
    @users = User.paginate(page: params[:page], per_page: 8)
  end

  def show
    @user = User.find_by(id: params[:id])
    @feed = @user.wall.paginate(page: params[:page], per_page: 10)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:success] = 'Please check your email to activate your account.'
      redirect_to root_url
    else
      flash[:danger] = 'Input is invalid.'
      render 'users/new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Successfully updated profile'
      redirect_to profile_path
    else
      flash.now[:danger] = 'Error'
      render 'users/edit'
    end
  end

  def unfriend # Remove friend
    User.find_by(id: params[:one]).unfriend(User.find_by(id: params[:two]))
    flash[:success] = 'Friend removed'
    redirect_to root_url
  end

  def java_client
    @users = User.all
    render xml: @users.to_xml
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar, :first_name,
                                 :last_name,
                                 :date_of_birth,
                                 :city,
                                 :country,
                                 :school,
                                 :university,
                                 :occupation)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3"><div id="user-<%= user.id %>" class="user-tile">
  <%= link_to full_name(user), user %><br>
  <%= user.username %>
  <%= user.email %>
  <%= image_tag user.avatar.url, class: 'img-responsive img-thumbnail' if user.avatar? %>
  <% if @current_user.is_friend?(user) %>
      <%= form_for :friend, url: remove_friend_path do |f| %>
          <%= hidden_field_tag :one, @current_user.id %>
          <%= hidden_field_tag :two, user.id %>
          <%= f.submit 'Remove friend', class: 'btn btn-danger' %>
      <% end %>
  <% end %>
</div></div>

app/views/users/edit.html.erb
<% provide :title, 'Edit User' %>
<div class="row"><div class="col-md-6 col-md-offset-3"><h1>Edit user</h1>
<%= form_for(@user, html: { multipart: true }) do |f| %>
    <%= f.label 'Username' %>
    <%= f.text_field :username, class: 'form-control' %>
    <%= f.label 'Avatar' %>
    <%= f.file_field :avatar, accept: 'image/jpeg,image/gif,image/png' %>
    <br>
    <h1>Questionnaire</h1>
    <%= f.label 'First Name' %>
    <%= f.text_field :first_name, class: 'form-control' %>
    <%= f.label 'Last Name' %>
    <%= f.text_field :last_name, class: 'form-control' %>
    <%= f.label 'Date of Birth' %>
    <%= f.date_field :date_of_birth, class: 'form-control' %>
    <%= f.label 'City' %>
    <%= f.text_field :city, class: 'form-control' %>
    <%= f.label 'Country' %>
    <%= f.text_field :country, class: 'form-control' %>
    <%= f.label 'School' %>
    <%= f.text_field :school, class: 'form-control' %>
    <%= f.label 'University' %>
    <%= f.text_field :university, class: 'form-control' %>
    <%= f.label 'Occupation' %>
    <%= f.text_field :occupation, class: 'form-control' %>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %></div></div>

<script type="text/javascript">
    $('#user_avatar').bind('change', check_size);
</script>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><h1>All users</h1></div>
</div>
<div class="row">
  <%= render @users %>
</div>

<%= will_paginate @users %>

<script>
    equalize();

</script>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3"><h1>Register</h1>
    <%= form_for @user, html: { multipart: true } do |f| %>
        <div id="info"></div>
        <%= f.label 'Username' %>
        <span id="hint"></span>
        <%= f.text_field :username, class: 'form-control' %>
        <%= f.label 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
        <%= f.label 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label 'Password confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.label 'Avatar' %>
        <%= f.file_field :avatar, accept: 'image/jpeg,image/gif,image/png' %>
        <hr>
        <h1>Questionnaire</h1>
        <%= f.label 'First Name' %>
        <%= f.text_field :first_name, class: 'form-control' %>
        <%= f.label 'Last Name' %>
        <%= f.text_field :last_name, class: 'form-control' %>
        <%= f.label 'Date of Birth' %>
        <%= f.date_field :date_of_birth, class: 'form-control' %>
        <%= f.label 'City' %>
        <%= f.text_field :city, class: 'form-control' %>
        <%= f.label 'Country' %>
        <%= f.text_field :country, class: 'form-control' %>
        <%= f.label 'School' %>
        <%= f.text_field :school, class: 'form-control' %>
        <%= f.label 'University' %>
        <%= f.text_field :university, class: 'form-control' %>
        <%= f.label 'Occupation' %>
        <%= f.text_field :occupation, class: 'form-control' %>
        <br>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %></div>
</div>


<script type="text/javascript">

    $('#user_avatar').bind('change', check_size);
    $('#user_username').bind('keyup', hint_username);
    $('#user_password').bind('keyup', password_hint);
    $('#user_password_confirmation').bind('keyup', password_matching)
</script>

app/views/users/show.html.erb
<% provide(:title, "#{@user.username}'s profile") %>
<div class="row main-header">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><h1><%= full_name @user %></h1></div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <h2><%= @user.email %></h2>
    <%= image_tag @user.avatar.url, class: 'img-responsive img-thumbnail' if @user.avatar? %>
    <% if @current_user.is_friend?(@user) %>
        <%= form_for :friend, url: remove_friend_path do |f| %>
            <%= hidden_field_tag :one, @current_user.id %>
            <%= hidden_field_tag :two, @user.id %>
            <%= f.submit 'Remove friend', class: 'btn btn-danger' %>
        <% end %>
    <% end %>
    <% unless @current_user.has_dialog_with(@user) %>
        <%= link_to 'Send message', dialogs_path(from: @current_user.id, to: @user.id), method: :post %>
    <% end %>
    <% if @current_user.is_friend? @user %>
        <p>This user is a friend of you.</p>
    <% else %>
        <% if FriendRequest.requested? @current_user, @user %>
            <p>You have already sent frienship request.</p>
        <% elsif current_user != @user %>
            <%= form_for FriendRequest.new do |f| %>
                <%= hidden_field_tag :from_id, @current_user.id %>
                <%= hidden_field_tag :to_id, @user.id %>
                <%= f.submit 'Add friend', class: 'btn btn-primary' %>
            <% end %>
        <% end %>
    <% end %></div>
  <div class="col-xs-12 col-md-3">
    <%= render 'shared/info', user: @user %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 friends">
    <% if @user.friends.any? %>
        <h1>Friends</h1>
        <%= render 'shared/friend_list' %>
    <% else %>
        <h1>This user has no friends.</h1>
    <% end %></div>
  <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">

    <div id="wall"><%= render @feed %></div>
    <%= will_paginate @feed %>
    <%= render 'shared/post_form' %></div>
</div>

<%= subscribe_to "/wall/#{@user.id}" %>
<script>
    PrivatePub.subscribe('/wall/<%= @user.id %>', function (data, channel) {
        $('#wall').prepend(form_input(data));
    });

    $('#post_content').keypress(check_key);
</script>