config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'search' => 'searchs#home'
  post 'search' => 'searchs#find'
  get 'password_resets/edit'
  get 'profile' => 'static_pages#profile'
  post 'unlike' => 'likes#destroy'
  get 'client/users' => 'users#java_client'
  get 'client/messages' => 'messages#java_client'

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'remove_friend' => 'users#unfriend'
  post 'quit_dialog' => 'dialogs#quit'
  delete 'unlike' => 'likes#destroy'
  resources :users do
    member do
      get 'dialogs' => 'dialogs#user'
    end

  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :friend_requests, only: [:create, :update]
  resources :posts, only: [:create, :destroy]
  resources :dialogs, only: [:create, :update, :new, :show]
  resources :messages, only: [:create]
  resources :likes, only: [:create]

end

app/models/dialog.rb
class Dialog < ActiveRecord::Base
  has_many :dialog_relationships, foreign_key: 'dialog_id'
  has_many :members, through: :dialog_relationships, source: :user
  has_many :messages
  has_many :notifications
  default_scope -> { order(:last_message_send => :desc) }


  def add_member(user)
    raise 'Already a member' if has_member?(user)
    DialogRelationship.create(user_id: user.id, dialog_id: id)
  end

  def add_members(users)
    users.each do |user|
      add_member(user)
    end
  end

  def actual_messages
    self.messages.all[10]
  end

  def has_member?(user)
    members.include?(user)
  end

  def remove_member(user)
    DialogRelationship.where('user_id = (?) AND dialog_id = (?)', user.id, id)[0].destroy
  end

end

app/controllers/dialogs_controller.rb
class DialogsController < ApplicationController
  before_action :is_logged_in?
  before_action :valid_user?, only: [:show]
  before_action :belongs_to_dialog?, only: [:quit]
  before_action :enough_members?, only: [:quit]
  before_action :user_is_normal?, only: [:quit]
  before_action :clear_notifications, only: [:show]

  def new

  end

  def create
    if params[:multi] == 'true' # Dialog with more than two members
      dialog = Dialog.create(name: params[:dialog][:name])
      input = params[:dialog][:string].split
      users = []
      creator = User.find_by(id: params[:dialog][:creator_id])
      if creator.nil?
        dialog.destroy
        flash.now[:danger] = 'Something wrong happened.'
        redirect_to root_url
      end
      users << creator

      input.each do |email|
        user = User.find_by(email: email)
        if user.nil? || user == creator
          dialog.destroy
          flash.now[:danger] = 'Wrong input'
          redirect_to root_url
          return
        end
        users << user
      end

      dialog.add_members users
      dialog.update_attribute(:last_message_send, Time.zone.now)
      redirect_to dialogs_user_path(current_user)
    else
      dialog = Dialog.create
      user_one = User.find_by(id: params[:from])
      user_two = User.find_by(id: params[:to])
      dialog.add_members([user_one, user_two])
      dialog.update_attribute(:name, "#{user_one.username} #{user_two.username}")
      dialog.update_attribute(:last_message_send, Time.zone.now)
      flash.now[:success] = 'Dialog successfully created!'
      redirect_to dialogs_user_path(current_user)
    end
  end

  def show
    @dialog = Dialog.find_by(id: params[:id])
    respond_to do |format|
      format.js
    end
  end


  def user # All dialogs which belong to current user
    @user = User.find_by(id: params[:id])
  end

  def quit
    dialog = Dialog.find_by(id: params[:dialog_id])
    user = User.find_by(id: params[:user_id])
    dialog.remove_member(user)
    redirect_to root_url
  end

  private
  def user_is_normal? # Protection
    unless current_user.id.to_s == params[:user_id]
      flash.now[:danger] = 'We think that you are a hacker'
      redirect_to root_url
    end
  end

  def valid_user?
    redirect_to root_url unless Dialog.find_by(id: params[:id]).members.include?(current_user)
  end

  def belongs_to_dialog?
    unless Dialog.find_by(id: params[:dialog_id]).members.include? User.find_by(id: params[:user_id])
      flash.now[:danger] = 'You are not a member of this dialog'
      redirect_to root_url
    end
  end

  def enough_members?
    unless Dialog.find_by(id: params[:dialog_id]).members.count > 2
      flash.now[:danger] = 'You cannot quit dialog with only two members'
      redirect_to root_url
    end
  end

  def clear_notifications
    Notification.where('user_id = (?) AND dialog_id = (?)', current_user.id, params[:id]).each do |n|
      n.destroy
    end

  end
end

app/helpers/dialogs_helper.rb
module DialogsHelper
end

app/views/dialogs/_dialog.html.erb
<h1><%= dialog_name dialog %></h1>
<% unless dialog.members.count < 3 %>
    <%= link_to 'Quit dialog', quit_dialog_path(user_id: current_user.id, dialog_id: dialog.id), method: :post %>
<% end %>
<div id="chat-scroll">
  <table id="chat" class="table">
    <%= render dialog.messages %>
  </table>
</div>
<%= subscribe_to "/dialogs/#{dialog.id}" %>
<div id="message-form">
  <%= render 'layouts/message_form' %>
</div>
<script>
    PrivatePub.subscribe('/dialogs/<%= dialog.id %>', function (data, channel) {
        $('#chat').append(formInput(data));
        $('#chat-scroll').scrollTop(document.getElementById('chat-scroll').scrollHeight);
    });
    $('#message_content').keypress(check_dialog_enter);
</script>

app/views/dialogs/new.html.erb
<% provide(:title, 'New Dialog') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3"><h1>Create dialog</h1>
    <%= form_for :dialog, url: dialogs_path do |f| %>
        <%= hidden_field_tag(:multi, true) %>
        <span>Enter list of user's emails you want to chat with in the dialog you are going to create.</span>
        <%= f.text_field :string, class: 'form-control' %>
        <%= f.label 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.hidden_field(:creator_id, value: current_user.id) %>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %></div>
</div>

app/views/dialogs/show.js.erb
$('#dialog_field').html('<%= escape_javascript render @dialog %>');
$('#chat-scroll').scrollTop(document.getElementById('chat-scroll').scrollHeight);

app/views/dialogs/user.html.erb
<% provide(:title, "#{@user.username}'s dialogs") %>
<div class="row">
  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
    <% if @user.dialogs.any? %>
        <h1>Your dialogs</h1>
        <div class="list-group">
          <% @user.dialogs.each do |dialog| %>
              <%= link_to dialog_name(dialog), dialog_path(dialog.id), class: 'list-group-item', remote: true %>
          <% end %>
        </div>
    <% else %>
        <h1>You have no dialogs</h1>
    <% end %>
    <%= link_to 'Create dialog', new_dialog_path %></div>
  <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9" id="dialog_field">

  </div>
</div>