config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'search' => 'searchs#home'
  post 'search' => 'searchs#find'
  get 'password_resets/edit'
  get 'profile' => 'static_pages#profile'
  post 'unlike' => 'likes#destroy'
  get 'client/users' => 'users#java_client'
  get 'client/messages' => 'messages#java_client'

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'remove_friend' => 'users#unfriend'
  post 'quit_dialog' => 'dialogs#quit'
  delete 'unlike' => 'likes#destroy'
  resources :users do
    member do
      get 'dialogs' => 'dialogs#user'
    end

  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :friend_requests, only: [:create, :update]
  resources :posts, only: [:create, :destroy]
  resources :dialogs, only: [:create, :update, :new, :show]
  resources :messages, only: [:create]
  resources :likes, only: [:create]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :from, class_name: 'User'
  belongs_to :to, class_name: 'User'
  has_many :likes, foreign_key: 'to_id'
  validates :content, presence: true, length: { maximum: 140 }
  mount_uploader :image, ImageUploader

  def liked?(user)
    !Like.where('from_id = (?) AND to_id = (?)', user.id, id)[0].nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_logged_in?
  before_action :valid_user?, only: [:destroy]

  def create
    user = User.find_by(id: params[:user][:id])
    @post = Post.new(from_id: params[:current_user][:id], to_id: params[:user][:id], content: params[:post][:content], image: params[:post][:image])
    if @post.save
      flash.now[:success] = 'Post successfully created.'
      PrivatePub.publish_to("/wall/#{user.id}", post: { content: @post.content, from: @post.from.username, image: @post.image.url })
    else
      flash.now[:danger] = 'An error occurred.'
    end
    redirect_to user
  end

  def destroy
    Post.find_by(id: params[:id]).destroy
    redirect_to root_url
  end

  private
  def valid_user? # Check if current user can delete posts
    redirect_to root_url unless @current_user.id.to_s == params[:user] || Post.find_by(id: params[:id]).to.id.to_s == params[:user]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="post" id="post-<%= post.id %>">

  <div class="row">
    <div class="col-md-2">
      <strong><%= post.from.username %></strong>
    </div>
    <div class="col-md-10">
      <p><%= post.content %></p>
      <%= image_tag post.image.url, class: 'img-responsive img-thumbnail post_image' if post.image? %>
      <% if post.from_id == @current_user.id || post.to_id == current_user.id %>
          <%= link_to 'Delete', post_path(post, user: @current_user.id), method: :delete, class: 'btn btn-default delete' %>
          <% end %>
      <p>Likes: <%= post.likes.count %></p>
      <% if !post.liked?(current_user) %>
          <%= link_to 'Like', likes_path(from_id: current_user.id, to_id: post.id), method: :post, remote: true %>
          <% else %>
          <%= link_to 'Unlike', unlike_path(from_id: current_user.id, to_id: post.id), method: :delete, remote: true %>
          <% end %>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
$('#post_content').val("");