config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'search' => 'searchs#home'
  post 'search' => 'searchs#find'
  get 'password_resets/edit'
  get 'profile' => 'static_pages#profile'
  post 'unlike' => 'likes#destroy'
  get 'client/users' => 'users#java_client'
  get 'client/messages' => 'messages#java_client'

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'remove_friend' => 'users#unfriend'
  post 'quit_dialog' => 'dialogs#quit'
  delete 'unlike' => 'likes#destroy'
  resources :users do
    member do
      get 'dialogs' => 'dialogs#user'
    end

  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :friend_requests, only: [:create, :update]
  resources :posts, only: [:create, :destroy]
  resources :dialogs, only: [:create, :update, :new, :show]
  resources :messages, only: [:create]
  resources :likes, only: [:create]

end

app/views/layouts/_flash.html.erb
<div id="flash">
  <% if flash.any? %>
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <% if logged_in? %>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Profile', profile_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Dialogs', dialogs_user_path(@current_user) %></li>
          <li><%= link_to 'Search', search_path %></li>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Register', signup_path %></li>
          <li><%= link_to 'Login', login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_message_form.html.erb
<%= form_for Message.new, remote: true do |f| %>
    <%= f.hidden_field :user_id, value: @current_user.id %>
    <%= f.hidden_field :dialog_id, value: @dialog.id %>
    <%= f.text_area :content, class: 'form-control' %>
    <br>
    <%= f.submit 'Submit', class: 'btn btn-primary', id: 'submit' %>
<% end %>

app/views/layouts/_notifications.html.erb
<% unless current_user.nil? %>
    <% if current_user.notifications.any? %>
        <div class="alert alert-info"><%= sanitize message %></div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/notifications' %>
<div class="container">
  <%= render 'layouts/flash' %><%= yield %></div>

</body>
</html>